name: Backstage - config Components
version: 1.0.0
level: component
nodes:
  - id: eslint-factory
    type: background-worker
    name: eslint-factory Service
    isTest: false
    properties:
      filepath: ../backstage/packages/cli/config/eslint-factory.js
      namespaces: ''
      technology: JavaScript Domain Service
    external: false
    x: 140
    'y': 50
  - id: eslint_backend
    type: background-worker
    name: eslint.backend Service
    isTest: false
    properties:
      filepath: ../backstage/packages/cli/config/eslint.backend.js
      namespaces: ''
      technology: JavaScript Domain Service
    external: false
    x: 600
    'y': 50
  - id: eslint
    type: background-worker
    name: eslint Service
    isTest: false
    properties:
      filepath: ../backstage/packages/cli/config/eslint.js
      namespaces: ''
      technology: JavaScript Domain Service
    external: false
    x: 7270
    'y': 370
  - id: getjestenvironment
    type: background-worker
    name: getJestEnvironment Service
    isTest: false
    properties:
      filepath: ../backstage/packages/cli-module-test-jest/config/getJestEnvironment.js
      namespaces: ''
      technology: JavaScript Domain Service
    external: false
    x: 1060
    'y': 50
  - id: jest
    type: background-worker
    name: jest Service
    isTest: false
    properties:
      filepath: ../backstage/packages/cli-module-test-jest/config/jest.js
      namespaces: ''
      technology: JavaScript Domain Service
    external: false
    x: 1520
    'y': 50
  - id: jestcachingmoduleloader
    type: background-worker
    name: jestCachingModuleLoader Service
    isTest: false
    properties:
      filepath: ../backstage/packages/cli-module-test-jest/config/jestCachingModuleLoader.js
      namespaces: ''
      technology: JavaScript Domain Service
    external: false
    x: 1980
    'y': 50
  - id: jestfiletransform
    type: background-worker
    name: jestFileTransform Service
    isTest: false
    properties:
      filepath: ../backstage/packages/cli-module-test-jest/config/jestFileTransform.js
      namespaces: ''
      technology: JavaScript Domain Service
    external: false
    x: 2440
    'y': 50
  - id: jestrejectnetworkrequests
    type: background-worker
    name: jestRejectNetworkRequests Service
    isTest: false
    properties:
      filepath: ../backstage/packages/cli-module-test-jest/config/jestRejectNetworkRequests.js
      namespaces: ''
      technology: JavaScript Domain Service
    external: false
    x: 2900
    'y': 50
  - id: jestsucrasetransform
    type: background-worker
    name: jestSucraseTransform Service
    isTest: false
    properties:
      filepath: ../backstage/packages/cli-module-test-jest/config/jestSucraseTransform.js
      namespaces: ''
      technology: JavaScript Domain Service
    external: false
    x: 3360
    'y': 50
  - id: jestswctransform
    type: background-worker
    name: jestSwcTransform Service
    isTest: false
    properties:
      filepath: ../backstage/packages/cli-module-test-jest/config/jestSwcTransform.js
      namespaces: ''
      technology: JavaScript Domain Service
    external: false
    x: 3820
    'y': 50
  - id: jestyamltransform
    type: background-worker
    name: jestYamlTransform Service
    isTest: false
    properties:
      filepath: ../backstage/packages/cli-module-test-jest/config/jestYamlTransform.js
      namespaces: ''
      technology: JavaScript Domain Service
    external: false
    x: 4280
    'y': 50
  - id: webpack-public-path
    type: background-worker
    name: webpack-public-path Service
    isTest: false
    properties:
      filepath: ../backstage/packages/cli-module-build/config/webpack-public-path.js
      namespaces: ''
      technology: JavaScript Domain Service
    external: false
    x: 4740
    'y': 50
  - id: error
    type: background-worker
    name: error Service (serialization)
    isTest: false
    properties:
      filepath: ../backstage/packages/errors/src/serialization/error.ts
      namespaces: ''
      technology: TypeScript Domain Service
    external: true
    x: 2670
    'y': 370
  - id: lint
    type: background-worker
    name: lint Service (commands)
    isTest: false
    properties:
      filepath: ../backstage/packages/repo-tools/src/commands/repo/schema/openapi/lint.ts
      namespaces: ''
      technology: TypeScript Domain Service
    external: true
    x: 5200
    'y': 50
  - id: list-deprecations
    type: background-worker
    name: list-deprecations Service (scripts)
    isTest: false
    properties:
      filepath: ../backstage/scripts/list-deprecations.js
      namespaces: ''
      technology: JavaScript Domain Service
    external: true
    x: 5660
    'y': 50
  - id: no-deprecated-bui-tokens_test
    type: background-worker
    name: no-deprecated-bui-tokens.test Service (no-deprecated-bui-tokens.test.ts)
    isTest: true
    properties:
      filepath: ../backstage/packages/eslint-plugin/src/no-deprecated-bui-tokens.test.ts
      namespaces: ''
      technology: TypeScript Domain Service
    external: true
    x: 6120
    'y': 50
  - id: no-forbidden-package-imports_test
    type: background-worker
    name: no-forbidden-package-imports.test Service (no-forbidden-package-imports.test.ts)
    isTest: true
    properties:
      filepath: ../backstage/packages/eslint-plugin/src/no-forbidden-package-imports.test.ts
      namespaces: ''
      technology: TypeScript Domain Service
    external: true
    x: 6580
    'y': 50
  - id: no-mixed-plugin-imports_test
    type: background-worker
    name: no-mixed-plugin-imports.test Service (no-mixed-plugin-imports.test.ts)
    isTest: true
    properties:
      filepath: ../backstage/packages/eslint-plugin/src/no-mixed-plugin-imports.test.ts
      namespaces: ''
      technology: TypeScript Domain Service
    external: true
    x: 7040
    'y': 50
  - id: no-relative-monorepo-imports_test
    type: background-worker
    name: no-relative-monorepo-imports.test Service (no-relative-monorepo-imports.test.ts)
    isTest: true
    properties:
      filepath: ../backstage/packages/eslint-plugin/src/no-relative-monorepo-imports.test.ts
      namespaces: ''
      technology: TypeScript Domain Service
    external: true
    x: 7500
    'y': 50
  - id: no-self-package-imports_test
    type: background-worker
    name: no-self-package-imports.test Service (no-self-package-imports.test.ts)
    isTest: true
    properties:
      filepath: ../backstage/packages/eslint-plugin/src/no-self-package-imports.test.ts
      namespaces: ''
      technology: TypeScript Domain Service
    external: true
    x: 7960
    'y': 50
  - id: no-top-level-material-ui-4-imports_test
    type: background-worker
    name: no-top-level-material-ui-4-imports.test Service (no-top-level-material-ui-4-imports.test.ts)
    isTest: true
    properties:
      filepath: ../backstage/packages/eslint-plugin/src/no-top-level-material-ui-4-imports.test.ts
      namespaces: ''
      technology: TypeScript Domain Service
    external: true
    x: 8420
    'y': 50
  - id: no-ui-css-imports-in-non-frontend_test
    type: background-worker
    name: no-ui-css-imports-in-non-frontend.test Service (no-ui-css-imports-in-non-frontend.test.ts)
    isTest: true
    properties:
      filepath: ../backstage/packages/eslint-plugin/src/no-ui-css-imports-in-non-frontend.test.ts
      namespaces: ''
      technology: TypeScript Domain Service
    external: true
    x: 8880
    'y': 50
  - id: no-undeclared-imports_test
    type: background-worker
    name: no-undeclared-imports.test Service (no-undeclared-imports.test.ts)
    isTest: true
    properties:
      filepath: ../backstage/packages/eslint-plugin/src/no-undeclared-imports.test.ts
      namespaces: ''
      technology: TypeScript Domain Service
    external: true
    x: 9340
    'y': 50
dependencies:
  - from: eslint-factory
    to: error
    type: direct-call
    description: References class type / calls methods
  - from: getjestenvironment
    to: error
    type: direct-call
    description: References class type / calls methods
  - from: jest
    to: error
    type: direct-call
    description: References class type / calls methods
  - from: jestcachingmoduleloader
    to: error
    type: direct-call
    description: References class type / calls methods
  - from: jestfiletransform
    to: error
    type: direct-call
    description: References class type / calls methods
  - from: jestrejectnetworkrequests
    to: error
    type: direct-call
    description: References class type / calls methods
  - from: jestsucrasetransform
    to: error
    type: direct-call
    description: References class type / calls methods
  - from: jestswctransform
    to: error
    type: direct-call
    description: References class type / calls methods
  - from: jestyamltransform
    to: error
    type: direct-call
    description: References class type / calls methods
  - from: webpack-public-path
    to: error
    type: direct-call
    description: References class type / calls methods
  - from: lint
    to: eslint
    type: direct-call
    description: Executes local class methods / functions
  - from: list-deprecations
    to: eslint
    type: direct-call
    description: Executes local class methods / functions
  - from: no-deprecated-bui-tokens_test
    to: eslint
    type: direct-call
    description: Executes local class methods / functions
  - from: no-forbidden-package-imports_test
    to: eslint
    type: direct-call
    description: Executes local class methods / functions
  - from: no-mixed-plugin-imports_test
    to: eslint
    type: direct-call
    description: Executes local class methods / functions
  - from: no-relative-monorepo-imports_test
    to: eslint
    type: direct-call
    description: Executes local class methods / functions
  - from: no-self-package-imports_test
    to: eslint
    type: direct-call
    description: Executes local class methods / functions
  - from: no-top-level-material-ui-4-imports_test
    to: eslint
    type: direct-call
    description: Executes local class methods / functions
  - from: no-ui-css-imports-in-non-frontend_test
    to: eslint
    type: direct-call
    description: Executes local class methods / functions
  - from: no-undeclared-imports_test
    to: eslint
    type: direct-call
    description: Executes local class methods / functions
