name: Backstage - readDurationFromConfig.test.ts Components
version: 1.0.0
level: component
nodes:
  - id: readdurationfromconfig_test
    type: background-worker
    name: readDurationFromConfig.test Service
    isTest: true
    properties:
      filepath: ../backstage/packages/config/src/readDurationFromConfig.test.ts
      namespaces: ''
      technology: TypeScript Domain Service
    external: false
    x: 370
    'y': 50
  - id: readdurationfromconfig
    type: background-worker
    name: readDurationFromConfig Service (readDurationFromConfig.ts)
    isTest: false
    properties:
      filepath: ../backstage/packages/config/src/readDurationFromConfig.ts
      namespaces: ''
      technology: TypeScript Domain Service
    external: true
    x: 140
    'y': 370
  - id: reader
    type: background-worker
    name: reader Service (reader.ts)
    isTest: false
    properties:
      filepath: ../backstage/packages/config/src/reader.ts
      namespaces: ''
      technology: TypeScript Domain Service
    external: true
    x: 600
    'y': 370
dependencies:
  - from: readdurationfromconfig_test
    to: readdurationfromconfig
    type: direct-call
    description: Executes local class methods / functions
  - from: readdurationfromconfig_test
    to: reader
    type: direct-call
    description: Executes local class methods / functions
