entityRef: blueprint/packages/cli-module-config
name: Cli-module-config Service Components
version: 1.0.0
level: component
nodes:
  - entityRef: blueprint/packages/cli-module-config/index
    type: background-worker
    name: index Service
    isTest: false
    properties:
      filepath: packages/cli-module-config/src/index.ts
      containerId: cli-module-config
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 1
      loc: 55
      sloc: 38
      churn: 1
      authorCount: 1
      topAuthorPercent: 1
      hotspotScore: 0
      classifications: []
      coupledFiles: []
      sinceDays: 500
    x: 140
    'y': 50
  - entityRef: blueprint/packages/cli-module-config/docs
    type: gateway-api
    name: docs UI Component
    isTest: false
    properties:
      filepath: packages/cli-module-config/src/commands/docs.ts
      containerId: cli-module-config
      technology: React Component
      classification: ui-import
    forensics:
      complexity: 2
      loc: 79
      sloc: 54
      churn: 1
      authorCount: 1
      topAuthorPercent: 1
      hotspotScore: 0
      classifications: []
      coupledFiles: []
      sinceDays: 500
    x: 600
    'y': 50
  - entityRef: blueprint/packages/cli-module-config/print
    type: background-worker
    name: print Service
    isTest: false
    properties:
      filepath: packages/cli-module-config/src/commands/print.ts
      containerId: cli-module-config
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 9
      loc: 105
      sloc: 81
      churn: 1
      authorCount: 1
      topAuthorPercent: 1
      hotspotScore: 0
      classifications: []
      coupledFiles: []
      sinceDays: 500
    x: 1060
    'y': 50
  - entityRef: blueprint/packages/cli-module-config/schema
    type: background-worker
    name: schema Service
    isTest: false
    properties:
      filepath: packages/cli-module-config/src/commands/schema.ts
      containerId: cli-module-config
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 3
      loc: 71
      sloc: 50
      churn: 1
      authorCount: 1
      topAuthorPercent: 1
      hotspotScore: 0
      classifications: []
      coupledFiles: []
      sinceDays: 500
    x: 1520
    'y': 50
  - entityRef: blueprint/packages/cli-module-config/validate
    type: background-worker
    name: validate Service
    isTest: false
    properties:
      filepath: packages/cli-module-config/src/commands/validate.ts
      containerId: cli-module-config
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 1
      loc: 62
      sloc: 43
      churn: 1
      authorCount: 1
      topAuthorPercent: 1
      hotspotScore: 0
      classifications: []
      coupledFiles: []
      sinceDays: 500
    x: 1980
    'y': 50
  - entityRef: blueprint/packages/cli-module-config/config
    type: background-worker
    name: config Service
    isTest: false
    properties:
      filepath: packages/cli-module-config/src/lib/config.ts
      containerId: cli-module-config
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 13
      loc: 135
      sloc: 99
      churn: 1
      authorCount: 1
      topAuthorPercent: 1
      hotspotScore: 0
      classifications:
        - knowledge-silo
      coupledFiles: []
      sinceDays: 500
    x: 1290
    'y': 370
dependencies:
  - from: blueprint/packages/cli-module-config/docs
    to: blueprint/packages/backend-plugin-api/types
    type: direct-call
    description: Calls module / service
  - from: blueprint/packages/cli-module-config/docs
    to: blueprint/packages/cli-module-config/config
    type: direct-call
    description: Calls module / service
  - from: blueprint/packages/cli-module-config/print
    to: blueprint/packages/cli-module-config/config
    type: direct-call
    description: Calls module / service
  - from: blueprint/packages/cli-module-config/print
    to: blueprint/packages/cli-module-config/config
    type: direct-call
    description: Calls module / service
  - from: blueprint/packages/cli-module-config/schema
    to: blueprint/packages/cli-module-config/config
    type: direct-call
    description: Calls module / service
  - from: blueprint/packages/cli-module-config/schema
    to: blueprint/packages/backend-plugin-api/types
    type: direct-call
    description: Calls module / service
  - from: blueprint/packages/cli-module-config/validate
    to: blueprint/packages/cli-module-config/config
    type: direct-call
    description: Calls module / service
  - from: blueprint/packages/frontend-plugin-api/createextension-test
    to: blueprint/packages/cli-module-config/schema
    type: direct-call
    description: Calls module / service
  - from: blueprint/packages/frontend-plugin-api/resolveextensiondefinition
    to: blueprint/packages/cli-module-config/schema
    type: direct-call
    description: Calls module / service
