version: https://blueprint.mzworthington.co.uk/schemas/v3/blueprint.schema.json
level: component
metaData:
  entityRef: blueprint/packages/config
  name: Config Service Components
  source:
    remoteUrl: https://github.com/backstage/backstage
    defaultBranch: master
    scannedAtCommit: 88690199d13ee94c3285f1ee219ae4339056c133
    scanRoot: .
nodes:
  - entityRef: blueprint/packages/config/readdurationfromconfig
    type: background-worker
    name: readDurationFromConfig Service
    isTest: false
    properties:
      filepath: packages/config/src/readDurationFromConfig.ts
      containerId: config
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 53
      loc: 311
      sloc: 216
      churn: 1
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 1
        - 0
      authorCount: 1
      topAuthorPercent: 1
      authors:
        - email: poldsberg@gmail.com
          commits: 1
      hotspotScore: 0
      classifications:
        - knowledge-silo
      sinceDays: 90
  - entityRef: blueprint/packages/config/reader
    type: background-worker
    name: reader Service
    isTest: false
    properties:
      filepath: packages/config/src/reader.ts
      containerId: config
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 85
      loc: 485
      sloc: 381
      churn: 1
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 1
        - 0
      authorCount: 1
      topAuthorPercent: 1
      authors:
        - email: poldsberg@gmail.com
          commits: 1
      hotspotScore: 0
      classifications:
        - knowledge-silo
      sinceDays: 90
  - entityRef: blueprint/packages/config/types
    type: background-worker
    name: types Service
    isTest: false
    properties:
      filepath: packages/config/src/types.ts
      containerId: config
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 1
      loc: 151
      sloc: 28
      churn: 1
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 1
        - 0
      authorCount: 1
      topAuthorPercent: 1
      authors:
        - email: poldsberg@gmail.com
          commits: 1
      hotspotScore: 0
      sinceDays: 90
  - entityRef: blueprint/packages/config/readdurationfromconfig-test
    type: background-worker
    name: readDurationFromConfig.test Service
    isTest: true
    properties:
      filepath: packages/config/src/readDurationFromConfig.test.ts
      containerId: config
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 1
      loc: 269
      sloc: 234
      churn: 1
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 1
        - 0
      authorCount: 1
      topAuthorPercent: 1
      authors:
        - email: poldsberg@gmail.com
          commits: 1
      hotspotScore: 0
      sinceDays: 90
  - entityRef: blueprint/packages/config/reader-test
    type: background-worker
    name: reader.test Service
    isTest: true
    properties:
      filepath: packages/config/src/reader.test.ts
      containerId: config
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 1
      loc: 795
      sloc: 720
      churn: 1
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 1
        - 0
      authorCount: 1
      topAuthorPercent: 1
      authors:
        - email: poldsberg@gmail.com
          commits: 1
      hotspotScore: 0
      sinceDays: 90
  - entityRef: blueprint/packages/config/index
    type: background-worker
    name: index Service
    isTest: false
    properties:
      filepath: packages/config/src/index.ts
      containerId: config
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 1
      loc: 32
      sloc: 9
      churn: 1
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 1
        - 0
      authorCount: 1
      topAuthorPercent: 1
      authors:
        - email: poldsberg@gmail.com
          commits: 1
      hotspotScore: 0
      sinceDays: 90
  - entityRef: blueprint/packages/config/deprecatedtypes
    type: background-worker
    name: deprecatedTypes Service
    isTest: false
    properties:
      filepath: packages/config/src/deprecatedTypes.ts
      containerId: config
      technology: TypeScript Domain Service
      classification: default
    forensics:
      complexity: 1
      loc: 56
      sloc: 10
      churn: 1
      churnByWeek:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 1
        - 0
      authorCount: 1
      topAuthorPercent: 1
      authors:
        - email: poldsberg@gmail.com
          commits: 1
      hotspotScore: 0
      sinceDays: 90
  - entityRef: blueprint/packages/cli-common/errors
    type: background-worker
    name: errors Service (External)
    external: true
    properties:
      filepath: packages/cli-common/src/errors.ts
      containerId: cli-common
      technology: TypeScript Domain Service
      classification: default
    x: 280
    y: 100
dependencies:
  - from: blueprint/packages/config/readdurationfromconfig
    to: blueprint/packages/cli-common/errors
    type: direct-call
    description: Calls module / service
  - from: blueprint/packages/config/readdurationfromconfig
    to: blueprint/packages/config/types
    type: direct-call
    description: Calls module / service
  - from: blueprint/packages/config/readdurationfromconfig
    to: blueprint/packages/config/types
    type: direct-call
    description: Calls module / service
  - from: blueprint/packages/config/reader
    to: blueprint/packages/config/types
    type: direct-call
    description: Calls module / service
  - from: blueprint/packages/config/reader
    to: blueprint/packages/config/types
    type: direct-call
    description: Calls module / service
  - from: blueprint/packages/config/readdurationfromconfig-test
    to: blueprint/packages/config/readdurationfromconfig
    type: direct-call
    description: Calls module / service
  - from: blueprint/packages/config/readdurationfromconfig-test
    to: blueprint/packages/config/reader
    type: direct-call
    description: Calls module / service
  - from: blueprint/packages/config/reader-test
    to: blueprint/packages/config/reader
    type: direct-call
    description: Calls module / service
  - from: blueprint/packages/config/deprecatedtypes
    to: blueprint/packages/config/types
    type: direct-call
    description: Calls module / service
