name: Designer - application Components
version: 1.0.0
level: component
parent_ref: designer/application
nodes:
- id: actioncontrols
  type: gateway-api
  name: ActionControls UI Component (ui)
  external: true
  properties:
    filepath: app/packages/designer/src/ui/features/workspace/components/ActionControls/ActionControls.tsx
    namespaces: ''
    technology: React Component
  is_test: false
  x: 100.0
  y: 100.0
- id: appcontext
  type: gateway-api
  name: AppContext UI Component
  external: false
  properties:
    filepath: app/packages/designer/src/application/context/AppContext.tsx
    namespaces: ''
    technology: React Component
  is_test: false
  x: 420.0
  y: 100.0
- id: blueprintnode
  type: gateway-api
  name: BlueprintNode UI Component (ui)
  external: true
  properties:
    filepath: app/packages/designer/src/ui/features/workspace/components/Canvas/BlueprintNode.tsx
    namespaces: ''
    technology: React Component
  is_test: false
  x: 740.0
  y: 100.0
- id: canvas
  type: gateway-api
  name: Canvas UI Component (ui)
  external: true
  properties:
    filepath: app/packages/designer/src/ui/features/workspace/components/Canvas/Canvas.tsx
    namespaces: ''
    technology: React Component
  is_test: false
  x: 1060.0
  y: 100.0
- id: db
  type: background-worker
  name: db Service (infrastructure)
  external: true
  properties:
    filepath: app/packages/designer/src/infrastructure/db/db.ts
    namespaces: ''
    technology: TypeScript Domain Service
  is_test: false
  x: 100.0
  y: 300.0
- id: defaultdata
  type: background-worker
  name: defaultData Service
  external: false
  properties:
    filepath: app/packages/designer/src/application/store/defaultData.ts
    namespaces: ''
    technology: TypeScript Domain Service
  is_test: false
  x: 420.0
  y: 300.0
- id: designsystempage
  type: gateway-api
  name: DesignSystemPage UI Component (ui)
  external: true
  properties:
    filepath: app/packages/designer/src/ui/features/designSystem/DesignSystemPage.tsx
    namespaces: ''
    technology: React Component
  is_test: false
  x: 740.0
  y: 300.0
- id: diagramstate
  type: gateway-api
  name: diagramState UI Component
  external: false
  properties:
    filepath: app/packages/designer/src/application/store/states/diagramState.ts
    namespaces: ''
    technology: React Component
  is_test: false
  x: 1060.0
  y: 300.0
- id: diffmenu
  type: gateway-api
  name: DiffMenu UI Component (ui)
  external: true
  properties:
    filepath: app/packages/designer/src/ui/features/workspace/components/DiffMenu/DiffMenu.tsx
    namespaces: ''
    technology: React Component
  is_test: false
  x: 100.0
  y: 500.0
- id: filesync
  type: background-worker
  name: fileSync Service (infrastructure)
  external: true
  properties:
    filepath: app/packages/designer/src/infrastructure/fileSystem/fileSync.ts
    namespaces: ''
    technology: TypeScript Domain Service
  is_test: false
  x: 420.0
  y: 500.0
- id: frontend-client
  type: gateway-api
  name: React Web Application (Frontend Client Host)
  external: true
  is_test: false
  x: 740.0
  y: 500.0
- id: header
  type: gateway-api
  name: Header UI Component (ui)
  external: true
  properties:
    filepath: app/packages/designer/src/ui/features/workspace/components/Header/Header.tsx
    namespaces: ''
    technology: React Component
  is_test: false
  x: 1060.0
  y: 500.0
- id: iostate
  type: background-worker
  name: ioState Service
  external: false
  properties:
    filepath: app/packages/designer/src/application/store/states/ioState.ts
    namespaces: ''
    technology: TypeScript Domain Service
  is_test: false
  x: 100.0
  y: 700.0
- id: layoututils
  type: gateway-api
  name: layoutUtils UI Component
  external: false
  properties:
    filepath: app/packages/designer/src/application/store/layoutUtils.ts
    namespaces: ''
    technology: React Component
  is_test: false
  x: 420.0
  y: 700.0
- id: logger
  type: background-worker
  name: logger Service (infrastructure)
  external: true
  properties:
    filepath: app/packages/designer/src/infrastructure/logging/logger.ts
    namespaces: ''
    technology: TypeScript Domain Service
  is_test: false
  x: 740.0
  y: 700.0
- id: propertypanel
  type: gateway-api
  name: PropertyPanel UI Component (ui)
  external: true
  properties:
    filepath: app/packages/designer/src/ui/features/workspace/components/PropertyPanel/PropertyPanel.tsx
    namespaces: ''
    technology: React Component
  is_test: false
  x: 1060.0
  y: 700.0
- id: store
  type: background-worker
  name: store Service
  external: false
  properties:
    filepath: app/packages/designer/src/application/store/store.ts
    namespaces: ''
    technology: TypeScript Domain Service
  is_test: false
  x: 100.0
  y: 900.0
- id: uistate
  type: background-worker
  name: uiState Service
  external: false
  properties:
    filepath: app/packages/designer/src/application/store/states/uiState.ts
    namespaces: ''
    technology: TypeScript Domain Service
  is_test: false
  x: 420.0
  y: 900.0
- id: usebreadcrumbs
  type: gateway-api
  name: useBreadcrumbs UI Component (ui)
  external: true
  properties:
    filepath: app/packages/designer/src/ui/features/workspace/components/Breadcrumbs/useBreadcrumbs.ts
    namespaces: ''
    technology: React Component
  is_test: false
  x: 740.0
  y: 900.0
- id: usecodeviewer
  type: gateway-api
  name: useCodeViewer UI Component (ui)
  external: true
  properties:
    filepath: app/packages/designer/src/ui/features/workspace/components/CodeViewer/useCodeViewer.ts
    namespaces: ''
    technology: React Component
  is_test: false
  x: 1060.0
  y: 900.0
- id: usesearchbar
  type: gateway-api
  name: useSearchbar UI Component (ui)
  external: true
  properties:
    filepath: app/packages/designer/src/ui/features/workspace/components/Searchbar/useSearchbar.ts
    namespaces: ''
    technology: React Component
  is_test: false
  x: 100.0
  y: 1100.0
- id: useurlsync
  type: gateway-api
  name: useUrlSync UI Component (ui)
  external: true
  properties:
    filepath: app/packages/designer/src/ui/features/workspace/hooks/useUrlSync.ts
    namespaces: ''
    technology: React Component
  is_test: false
  x: 420.0
  y: 1100.0
- id: workspacepage
  type: gateway-api
  name: WorkspacePage UI Component (ui)
  external: true
  properties:
    filepath: app/packages/designer/src/ui/features/workspace/WorkspacePage.tsx
    namespaces: ''
    technology: React Component
  is_test: false
  x: 740.0
  y: 1100.0
dependencies:
- from: frontend-client
  to: appcontext
  type: direct-call
  description: Renders AppContext layout component
- from: appcontext
  to: filesync
  type: direct-call
  description: Executes local class methods / functions
- from: appcontext
  to: logger
  type: direct-call
  description: Executes local class methods / functions
- from: appcontext
  to: store
  type: direct-call
  description: Executes local class methods / functions
- from: frontend-client
  to: layoututils
  type: direct-call
  description: Renders layoutUtils layout component
- from: frontend-client
  to: diagramstate
  type: direct-call
  description: Renders diagramState layout component
- from: diagramstate
  to: uistate
  type: direct-call
  description: Executes local class methods / functions
- from: diagramstate
  to: iostate
  type: direct-call
  description: Executes local class methods / functions
- from: diagramstate
  to: layoututils
  type: direct-call
  description: Executes local class methods / functions
- from: diagramstate
  to: defaultdata
  type: direct-call
  description: Executes local class methods / functions
- from: diagramstate
  to: db
  type: direct-call
  description: Executes local class methods / functions
- from: iostate
  to: diagramstate
  type: direct-call
  description: Executes local class methods / functions
- from: iostate
  to: db
  type: direct-call
  description: Executes local class methods / functions
- from: store
  to: uistate
  type: direct-call
  description: Executes local class methods / functions
- from: store
  to: diagramstate
  type: direct-call
  description: Executes local class methods / functions
- from: store
  to: iostate
  type: direct-call
  description: Executes local class methods / functions
- from: designsystempage
  to: store
  type: direct-call
  description: Executes local class methods / functions
- from: workspacepage
  to: store
  type: direct-call
  description: Executes local class methods / functions
- from: actioncontrols
  to: store
  type: direct-call
  description: Executes local class methods / functions
- from: usebreadcrumbs
  to: store
  type: direct-call
  description: Executes local class methods / functions
- from: blueprintnode
  to: store
  type: direct-call
  description: Executes local class methods / functions
- from: canvas
  to: store
  type: direct-call
  description: Executes local class methods / functions
- from: usecodeviewer
  to: store
  type: direct-call
  description: Executes local class methods / functions
- from: diffmenu
  to: store
  type: direct-call
  description: Executes local class methods / functions
- from: header
  to: store
  type: direct-call
  description: Executes local class methods / functions
- from: propertypanel
  to: store
  type: direct-call
  description: Executes local class methods / functions
- from: usesearchbar
  to: store
  type: direct-call
  description: Executes local class methods / functions
- from: useurlsync
  to: store
  type: direct-call
  description: Executes local class methods / functions
